//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatingweb.WebChatDataEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountPerstionaluserInfo
    {
        public int ChatId { get; set; }
        public string LoginUserMobileNo { get; set; }
        public string LoginUserName { get; set; }
        public string AddNewUserPhone { get; set; }
        public string NewUerName { get; set; }
        public string NewuserPictureProfile { get; set; }
        public Nullable<int> NewUserStatus { get; set; }
    }
}
