//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatingweb.WebChatDataEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admintbl
    {
        public int AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminPassword { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string AdminCreteDate { get; set; }
        public string AdminLoginDate { get; set; }
        public Nullable<int> AdminStatus { get; set; }
        public string AdminProfile { get; set; }
    }
}
