//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatingweb.WebChatDataEDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountLogin
    {
        public int LoginId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserMobile { get; set; }
        public string UserPassword { get; set; }
        public string UserRagisterDate { get; set; }
        public string UserLoginDate { get; set; }
        public Nullable<int> RagisterStatus { get; set; }
        public Nullable<int> Loginstatus { get; set; }
        public string UserLastLoginDate { get; set; }
    }
}
